### ISSUE TITLE
User channel name inheritance in config.js

### ISSUE THREAD

**Issue by muigorick** [mohamed-tayeh/Minimal-Pomo-Timer#15]
It looks like one message doesn't inherit the users' channel name; instead, it uses a predefined one. 

https://github.com/mohamed-tayeh/Minimal-Pomo-Timer/blob/a9648f584c358763cae1607e363b5fa9a6e4d8b1/configs.js#L56

**Comment by mohamed-tayeh** [comment]
@muigorick It can be edited to change the message, or would it be preferred to have something like this:

```
const workRemindMsg = 'Time to get ready for focus {channel}💻'; 
```

Prior it would have been edited to be as:
```
const workRemindMsg = 'Time to get ready for focus @MuigoRick 💻'; 
```
