### ISSUE TITLE
Timer Remove command, and Request for Long Break distinction

### ISSUE THREAD

**Issue by TheAntiqueFox** [mohamed-tayeh/Minimal-Pomo-Timer#28]
Hello again!
I noticed that there was commands to add a specific amount of time, and set the clock to a specific time, but I would also like a command to reduce the clock by a specific amount (secs, and also xx:xx).

Also, I would like to have more distinction between short and long breaks. Currently, they both receive the same automatic break label and break msg. I treat my short and long breaks differently, so it would be useful if I could create more distinction both in the label and in the message in chat, so that the difference was better communicated!

thank you so much moh <3,
fox

**Comment by mohamed-tayeh** [comment]
For sure fox, I added additional configs for the long break (label, chat message and sound). For the `!timer sub xx:xx` command was not in the documentation, so I added it there
