### ISSUE TITLE
Way to adjust the volume of each sound alert in the config

### ISSUE THREAD

**Issue by TheAntiqueFox** [mohamed-tayeh/Minimal-Pomo-Timer#30]
Maybe I am being silly, and simply can't figure it out, but I would love to have some way to change how loud the pomo timer alarms are and by adjusting my desktop audio!
If I am simply missing how to do this, please tell me how to <3
thank you again moh,
Fox

**Comment by mohamed-tayeh** [comment]
I believe we have resolved this privately @TheAntiqueFox please re-open if any issue persists:)

**Comment by churchkey90** [comment]
I would also like to know how to adjust how loud the alarm sound is

**Comment by mohamed-tayeh** [comment]
Thanks for reaching out @churchkey90 

You can do it directly through OBS filters as follows: 

1. Click on triple dots &   Click on filter in opened menu 
![image](https://github.com/mohamed-tayeh/Minimal-Pomo-Timer/assets/35163331/8f12fcad-ae04-4f30-ab88-4f447ece877a)

**Comment by churchkey90** [comment]
Thank you so much. I am using Streamlabs Desktop and forgot to activate the option to change audio setting right in Streamlabs to adjust the computer audio output separately from the alarms. Thank you for the quick reply.

**Comment by mohamed-tayeh** [comment]
@churchkey90 My pleasure! Feel free to ask my anything
