### ISSUE TITLE
changing values on config file doesn't have any effect

### ISSUE THREAD

**Issue by y0ur5h4d0w** [mohamed-tayeh/Minimal-Pomo-Timer#34]
hi! everytime i try to set a custom timer for the work and the break i always get the default 90 minutes for the work and 15 minutes for the break even though on the config file i've set 1800 seconds (30 minutes) for the work and 300 seconds (5 minutes) for the break :thinking:  did i do something wrong? same goes for the pomo counter, i've set 4 and it still stay 5 :thinking: this is my config file values:

`  // Time Configuration
  const workTime = 1800; // in seconds
  const breakTime = 300; // in seconds
  const longBreakTime = 900; // in seconds
  const longBreakEvery = 4; // long break every x pomos
  const defaultPomoNumber = 4;
  const workTimeRemind = 25;
  const sendWorkTimeRemind = true;
  const startingTime = 1800;
  const noLastBreak = true;
  const showHours = false; // true: time in hh:mm:ss; false: time in mm:ss always
  const showHoursIf00 = false; // true: will show 00:mm:ss, false: will show mm:ss when hours is 0 `

**Comment by y0ur5h4d0w** [comment]
i've even tried to wipe the folder and the config.js replacing with the latest 1.2.2 version but it still doens't want to change the values :thinking:

**Comment by mohamed-tayeh** [comment]
Are you sure your OBS overlay is pointing to the right file? I would make sure you are starting the setup again when re-downloading

**Comment by mohamed-tayeh** [comment]
It has been sometime since i got a response so I will be closing this issue as regarding it as a human error rather than code error the timer works for many 👍
