### ISSUE TITLE
Timer not working

### ISSUE THREAD

**Issue by Sweedy2705** [mohamed-tayeh/Minimal-Pomo-Timer#44]
Goodtimezone,

When i want to use the timer in my stream the pomo timer wont do it. 
So when i typ !start timer it will do the count down.
But after that it just stoped it will stay on the 50 minuts what the name work and the pomo numbers stay 0/4 

Any ideas what i do wrong ?? 

Greats,
Sweedy!

**Comment by mohamed-tayeh** [comment]
`!start` is the initial start of the stream. Let's say you would like to have 5 min start time when people are joining the stream and getting ready to work.

`!timer start` would start the pomo timers.

Please let me know if that works for you.

**Comment by Sweedy2705** [comment]
It did thank you !
